[package]
name = "duden-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
html5ever = "0.26.0"
regex = "1.10.3"
reqwest = { version = "0.11.26", default-features = false, features = ["rustls-tls"] }
scraper = "0.19.0"
